spring.application.name=agregadorinvestimentos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${DB_HOST}:3307/agregadorinvest
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_SECRET}
